spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/thepustakaridb'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: '8080'
springdoc:
  swagger-ui:
    url: 'http://localhost:8080/swagger-ui.html'
